language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install: pip install tox
script: tox -e py$(echo "$TRAVIS_PYTHON_VERSION" | sed 's|\.||')
