addons:
  apt:
    packages:
      - pandoc
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false

install: pip install pypandoc tox
script: tox -e py$(echo "$TRAVIS_PYTHON_VERSION" | sed 's|\.||')
